import NewsSection from "@/components/pages/mobile/blog/newsSection";
import Head from "next/head";
import styled from "styled-components";

export default function News() {
    return(
        <>
            <Head>
                <title>News | Vincebet</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Content>
                <NewsSection />
            </Content>
        </>
    )
}

const Content = styled.main`
    margin: 0 auto;
    max-width: 1440px;
`