
import NewsSection from "@/components/pages/mobile/blog/newsSection";
import { INewsContent, newsContent } from "@/constants/news";
import CheckDevice from "@/services";
import { GetStaticPaths, GetStaticProps } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";


export default function NewsSlug() {
    const router = useRouter()
    const [ currentNews, setCurrentNews ] = useState<INewsContent>(newsContent.find((item) => item.slug.includes(decodeURIComponent(router.query.slug as string)))!)

    CheckDevice()

    return(
        <>
            <Head>
                <title>News | Vincebet</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <NewsSection content={currentNews} />
            </main>
        </>
    )
}

export const getStaticPaths: GetStaticPaths = async () => {
    return {
        paths: [
            {
                params: { slug: decodeURI("สวัสดี") }
            },
            {
                params: { slug: decodeURI("สวัสดีปี") }
            },
            {
                params: { slug: decodeURI("สวัสดีปีใหม่") }
            },
        ],
        fallback: false
    }
}

export const getStaticProps: GetStaticProps = async () => {
    return {
        props: {
            posts: [
                { slug: decodeURI("สวัสดี"), content: newsContent[0] },
                { slug: decodeURI("สวัสดีปี"), content: newsContent[1] },
                { slug: decodeURI("สวัสดีปีใหม่") },
            ]
        }
    }
}