import styled from "styled-components";
import Head from "next/head";
import KnowledgeSection from "@/components/pages/desktop/blog/knowledgeSection";
import NewsSection from "@/components/pages/desktop/blog/newsSection";
import CheckDevice from "@/services";

export default function Blog(){
    CheckDevice()
    return(
        <>
            <Head>
                <title>Blog | Vincebet</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Content>
                <KnowledgeSection />
                <NewsSection />
            </Content>
        </>
    )
}

const Content = styled.main`
    max-width: 1440px;
    margin: 0 auto;
`