import Head from 'next/head'
import styled from 'styled-components'
import HeroSection from '@/components/pages/desktop/home/heroSection'
import CasinoSection from '@/components/pages/desktop/home/casinoSection'
import TypeCasinoSection from '@/components/pages/desktop/home/typecasinoSection'
import HowtoSection from '@/components/pages/desktop/home/howtoSection'
import GameCasinoSection from '@/components/pages/desktop/home/gamecasinoSecrion'
import GameSlotSection from '@/components/pages/desktop/home/gameslotSection'
import PromotionSection from '@/components/pages/desktop/home/promotionSection'
import BlogSection from '@/components/pages/desktop/home/blogSection'
import NewsSection from '@/components/pages/desktop/home/newsSection'
import ReviewSection from '@/components/pages/desktop/home/reviewSection'
import CheckDevice from '@/services'

export default function Home() {

  CheckDevice()
  
  return (
    <>
      <Head>
        <title>Home | Vincebet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content>
        <HeroSection />
        <CasinoSection />
        <TypeCasinoSection />
        <HowtoSection />
        <GameCasinoSection />
        <GameSlotSection />
        <PromotionSection />
        <BlogSection />
        <NewsSection />
        <ReviewSection />
      </Content>
    </>
  )
}

const Content = styled.main`
  width: 100%;
  height: fit-content;
  max-width: 1440px;
  /* min-width: 1440px; */

  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;

  gap: 10px;
  margin: auto;
` 
