import styled from "styled-components";
import Head from "next/head";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Image from "next/legacy/image"
import ButtonHover from "@/components/_reduce/ButtonHover";
import "aos/dist/aos.css";
import AOS from "aos";
import 'aos/dist/aos.css';
import { useEffect } from "react";

export default function RestPage(){

    useEffect(() => {
        AOS.init();
    }, [])

    return(
        <>
            <Head>
                <title>Test | Vincebet</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Content>
                <Container>
                    <TestImg data-aos="fade-up" src="https://placehold.co/500x500" />
                </Container>
            </Content>
        </>
    )
}

const TestImg = styled.img`
    width: 500px;
    height: 500px;
`

const Container = styled.div`
    width: 100%;
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
`

const Content = styled.main`
    width: 100vw;
    height: 100vh;
`