import Head from 'next/head'
import styled from 'styled-components'
import HeroSection from '@/components/pages/mobile/home/heroSection'
import CasinoSection from '@/components/pages/mobile/home/casinoSection'
import TypeCasinoSection from '@/components/pages/mobile/home/typecasinoSection'
import HowtoSection from '@/components/pages/mobile/home/howtoSection'
import GameCasinoSection from '@/components/pages/mobile/home/gamecasinoSecrion'
import GameSlotSection from '@/components/pages/mobile/home/gameslotSection'
import PromotionSection from '@/components/pages/mobile/home/promotionSection'
import BlogSection from '@/components/pages/mobile/home/blogSection'
import NewsSection from '@/components/pages/mobile/home/newsSection'
import ReviewSection from '@/components/pages/mobile/home/reviewSection'
import CheckDevice from '@/services'

export default function Home() {

  CheckDevice()

  return (
    <>
      <Head>
        <title>Home | Vincebet</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background src="/assets/img/BG.jpg" />
      <Content>
        <HeroSection />
        <CasinoSection />
        <TypeCasinoSection />
        <HowtoSection />
        <GameCasinoSection />
        <GameSlotSection />
        <PromotionSection />
        <BlogSection />
        <NewsSection />
        <ReviewSection />
      </Content>
    </>
  )
}

const Background = styled.img`
  position: fixed;
  top: 0;
  left: 0;
  z-index: 0;
  width: 100vw;
  height: 100vh;
  object-fit: cover;
`

const Content = styled.main`
    width: 100%;
    height: auto;
    max-width: 744px;

    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;

    gap: 10px;
    margin: auto;
    padding-bottom: 0px;

` 
