import styled from "styled-components";
import Head from "next/head";
import CheckDevice from "@/services";
import Bar from "@/components/pages/mobile/newcasino/bar";
import { ReactNode, useState } from "react";
import GameHit from "@/components/pages/mobile/newcasino/gamehit";

export default function NewCasino(){

    const [ typegame , setTypegame ] = useState<ReactNode>(GameHit)
    
    CheckDevice()

    return(
        <>
            <Head>
                <title>Home | Vincebet</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Background src="/assets/img/BGnewcasino.jpg" />
            <Content>
                <Bar typegame={typegame} setTypegame={setTypegame} />

                    {typegame}

            </Content>
        </>
    )
}

const Background = styled.img`
  width: 100vw;
  height: 100vh;

  position: fixed;
  top: 0;
  right: 0;
  
  z-index: -1;

  object-fit: cover;
  object-position: right;
`

const Content = styled.main`
    width: 100%;
    height: auto;
    max-width: 744px;

    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;

    gap: 10px;
    margin: auto;
    padding-bottom: 65px;

    @media (min-width: 744px) {
        gap: 16px;
    }
` 
